name: Update-Configs
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install requests
      - run: python sweeper.py
      - run: |
          git config --global user.name "Officer-MmD-Bot"
          git config --global user.email "bot@github.com"
          git add data.txt
          if git diff --staged --quiet; then
            echo "No changes found in configs."
          else
            git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
          
